# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JMV5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1800, 950)
        # 禁止最大化
        widget.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        
        self.listView = QtWidgets.QListView(widget)
        self.listView.setGeometry(QtCore.QRect(10, 50, 271, 850))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(300, 10, 271, 31))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(widget)
        self.textEdit.setGeometry(QtCore.QRect(300, 50, 1481, 91))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 910, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(widget)
        self.pushButton_4.setGeometry(QtCore.QRect(1640, 150, 141, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(widget)
        self.tableWidget.setGeometry(QtCore.QRect(300, 190, 1481, 350))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(widget)
        self.tableWidget_2.setGeometry(QtCore.QRect(300, 590, 1481, 350))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(300, 150, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(300, 550, 81, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1630, 550, 151, 31))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "项目分析"))
        self.label.setText(_translate("widget", "对应SQL语句如下："))
        self.pushButton_3.setText(_translate("widget", "自定义SQL"))
        self.label_2.setText(_translate("widget", "分析列表："))
        self.pushButton_4.setText(_translate("widget", "导出汇总表"))
        self.label_3.setText(_translate("widget", "汇总表："))
        self.label_4.setText(_translate("widget", "清单表："))
        self.pushButton_5.setText(_translate("widget", "导出清单表"))
