# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '20241027.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionsanji = QtWidgets.QAction(MainWindow)
        self.actionsanji.setObjectName("actionsanji")
        self.action_4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        #font.setFamily("宋体")
        #font.setPointSize(10)
        self.action_4.setFont(font)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.menu.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menu_3.addAction(self.action_6)
        self.menu_3.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menu_4.addAction(self.action_7)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "在线分析工具"))
        self.menu.setTitle(_translate("MainWindow", "腾讯文档"))
        self.menu_2.setTitle(_translate("MainWindow", "项目分析"))
        self.menu_3.setTitle(_translate("MainWindow", "数据库"))
        self.menu_4.setTitle(_translate("MainWindow", "执行器"))
        self.action.setText(_translate("MainWindow", "【分系统研发投入】分析"))
        self.action_2.setText(_translate("MainWindow", "【分小组研发投入】分析"))
        self.action_3.setText(_translate("MainWindow", "【自定义】"))
        self.actionsanji.setText(_translate("MainWindow", "sanji"))
        self.action_4.setText(_translate("MainWindow", "批量下载"))
        self.action_5.setText(_translate("MainWindow", "自助分析"))
        self.action_6.setText(_translate("MainWindow", "新建连接"))
        self.action_7.setText(_translate("MainWindow", "Python脚本执行"))
        self.action_8.setText(_translate("MainWindow", "执行SQL"))
        self.action_9.setText(_translate("MainWindow", "文件导入"))