# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SETINPUT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setinput(object):
    def setupUi(self, setinput):
        setinput.setObjectName("setinput")
        setinput.resize(1024, 780)
        self.label_2 = QtWidgets.QLabel(setinput)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(setinput)
        self.textEdit.setGeometry(QtCore.QRect(30, 130, 961, 281))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(setinput)
        self.label_3.setGeometry(QtCore.QRect(30, 420, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(setinput)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 460, 961, 271))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(setinput)
        self.pushButton.setGeometry(QtCore.QRect(850, 740, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(setinput)
        self.lineEdit.setGeometry(QtCore.QRect(180, 30, 811, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(setinput)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(setinput)
        QtCore.QMetaObject.connectSlotsByName(setinput)

    def retranslateUi(self, setinput):
        _translate = QtCore.QCoreApplication.translate
        setinput.setWindowTitle(_translate("setinput", "自定义窗口"))
        self.label_2.setText(_translate("setinput", "请输入分析SQL："))
        self.label_3.setText(_translate("setinput", "请输入清单SQL："))
        self.pushButton.setText(_translate("setinput", "确认提交"))
        self.label.setText(_translate("setinput", "请输入标题："))
